name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 30m
          script: |
            cd /home/ubuntu/web/fermi
            git pull origin master
            /home/ubuntu/.nvm/versions/node/v22.15.0/bin/npm install
            /home/ubuntu/.nvm/versions/node/v22.15.0/bin/npm run build
            PORT=3002 /home/ubuntu/.nvm/versions/node/v22.15.0/bin/pm2 restart fermi-gateway --update-env
